defaults:
  - /schema/model: due
  - base


num_features: 128
depth: 1
snorm_coeff: 0.95
n_power_iterations: 1
dropout_rate: 0.01
activation_fn: relu
kernel: matern12
num_inducing_points: 10
num_inducing_point_refs: 20
beta: 1.0
