defaults:
  - /schema/trainer: trainer

deterministic: False
gpus: 0
auto_select_gpus: False
auto_scale_batch_size: False
accelerator: null
terminate_on_nan: True
max_epochs: 100
distributed_backend: null
